In [10]:
import numpy as np
from sympy import Matrix
import scipy
import scipy.linalg
import time

# Question 11

# System 1  

In [12]:
A1=np.array([[3,-1,1],[3,6,2],[3,3,7]])
b1=np.array([1,0,4])
x1=np.linalg.solve(A1,b1)
x1

array([ 0.03508772, -0.23684211,  0.65789474])

# System 2

In [13]:
A2=np.array([[10,-1,0],[-1,10,-2],[0,-2,10]])
b2=np.array([9,7,6])
x2=np.linalg.solve(A2,b2)
x2

array([0.99578947, 0.95789474, 0.79157895])

# System 3

In [21]:
A3=np.array([[10,5,0,0],[5,10,-4,0],[0,-4,8,-1],[0,0,-1,5]])
b3=np.array([6,25,-11,-11])
x3=np.linalg.solve(A3,b3)
x3

array([-0.79764706,  2.79529412, -0.25882353, -2.25176471])

# System 4

In [28]:
A4=np.array([[4,1,1,0,1],[-1,-2,1,1,0],[2,1,5,-1,-1],[-1,-1,-1,4,0],[0,2,-1,1,4]])
b4=np.array([6,6,6,6,6])
x4=np.linalg.solve(A4,b4)
x4

array([ 0.8       , -1.48571429,  2.        ,  1.82857143,  2.28571429])

# Question 13 

In [49]:
A1=np.array([[3,-1,1],[3,6,2],[3,3,7]])
P,L,U=scipy.linalg.lu(A1)
Matrix(A1)

Matrix([
[3, -1, 1],
[3,  6, 2],
[3,  3, 7]])

In [50]:
Matrix(P)

Matrix([
[1.0,   0,   0],
[  0, 1.0,   0],
[  0,   0, 1.0]])

In [45]:
Matrix(L)

Matrix([
[1.0,                 0,   0],
[1.0,               1.0,   0],
[1.0, 0.571428571428571, 1.0]])

In [59]:
Matrix(U)

Matrix([
[3.0, -1.0,              1.0],
[  0,  7.0,              1.0],
[  0,    0, 5.42857142857143]])

In [48]:
Matrix(np.dot(L,U))

Matrix([
[3.0, -1.0, 1.0],
[3.0,  6.0, 2.0],
[3.0,  3.0, 7.0]])

# Question 16

### Jacobi Method

In [131]:
A=np.array([[0.2,0.1,1,1,0],[0.1,4,-1,1,-1],[1,-1,60,0,-2],[1,1,0,8,4],[0,-1,-2,4,700]])
b=np.array([1,2,3,4,5])
#X_actual=np.linalg.solve(A,b).tolist()
X_actual=[7.859713071, 0.422926408, -0.073592239, -0.540643016, 0.010626163]
n=5
X=[]
x0=np.zeros(n)
X.append(x0)

#Initialize
xk=np.zeros(n)
N=0
while N <n:
    x=np.zeros(n)
    for i in range(n):
        xkm1=xk
        S=0
        for j in range(n):
            if (i!=j):
                S=S-A[i][j]*xkm1[j]
            
        x[i]=(S + b[i])/A[i][i]
    xk=x
    X.append(x)
    l=len(X)
    N=0
    for i in range(n):
        if abs(X[l-1][i]-X_actual[i])<0.01:
            N=N+1
    
l=len(X)
print("No of Iterations: ",l-1)
for i in range(l):
    print(X[i])

No of Iterations:  37
[0. 0. 0. 0. 0.]
[5.         0.5        0.05       0.5        0.00714286]
[ 2.          0.26428571 -0.0247619  -0.19107143  0.00514286]
[5.94702381 0.4928631  0.02124286 0.21439286 0.0085415 ]
[ 3.57538988  0.30517228 -0.04061796 -0.30925661  0.00668254]
[ 6.59678673e+00  4.79445550e-01 -4.28087540e-03  1.15884605e-02
  9.22994686e-03]
[ 4.7237393   0.33342048 -0.05164802 -0.38914401  0.00774933]
[ 7.03724991  0.46821785 -0.02291367 -0.13601964  0.00969529]
[ 5.56055761  0.35476907 -0.05916069 -0.44303111  0.00852353]
[ 7.33357449  0.45908455 -0.03647902 -0.2436776   0.01001225]
[ 6.17124084  0.37096334 -0.06424109 -0.4790885   0.00908691]
[ 7.53116629  0.45170256 -0.04636839 -0.32231898  0.01022691]
[ 6.61758558  0.38326522 -0.06765017 -0.50297206  0.00949749]
[ 7.66147852  0.44576521 -0.05358876 -0.37985509  0.01037122]
[ 6.94433665  0.39262243 -0.06991618 -0.51859108  0.00979715]
[ 7.74622507  0.4410096  -0.05886867 -0.42201846  0.01046736]
[ 7.18393084  0.3997

### Gauss-Seidel

In [60]:
#A=np.array([[0.2,0.1,1,1,0],[0.1,4,-1,1,-1],[1,-1,60,0,-2],[1,1,0,8,4],[0,-1,-2,4,700]])
#b=np.array([1,2,3,4,5])
#X_actual=[7.859713071, 0.422926408, -0.073592239, -0.540643016, 0.010626163]
A=np.array([[3,-1,1],[3,6,2],[3,3,7]])
b=np.array([1,0,4])
X_actual=np.linalg.solve(A,b).tolist()
n=3
X=[]
x0=np.zeros(n).tolist()
X.append(x0)

#Initialize
xk=np.zeros(n).tolist()

N=0
while N<n:
    x=np.zeros(n).tolist()
    for i in range(n):
        S=0
        for j in range(n):
            if (i!=j):
                S=S-A[i][j]*xk[j]
            
        m=(S + b[i])/A[i][i]
        xk[i]=m
        x[i]=m
    X.append(x)
    l=len(X)
    N=0
    for i in range(n):
        if abs(X[l-1][i]-X_actual[i])<0.01:
            N=N+1
    
    
l=len(X)
print("No of Iterations: ",l-1)
for i in range(l):
    print(X[i])

No of Iterations:  4
[0.0, 0.0, 0.0]
[0.3333333333333333, -0.16666666666666666, 0.5]
[0.11111111111111112, -0.22222222222222224, 0.619047619047619]
[0.05291005291005294, -0.2328042328042328, 0.6485260770975056]
[0.039556563366087184, -0.23595364071554548, 0.6555987474354821]


### Relaxation

In [3]:
A=np.array([[0.2,0.1,1,1,0],[0.1,4,-1,1,-1],[1,-1,60,0,-2],[1,1,0,8,4],[0,-1,-2,4,700]])
b=np.array([1,2,3,4,5])
X_actual=[7.859713071, 0.422926408, -0.073592239, -0.540643016, 0.010626163]
#System 1
#A=np.array([[3,-1,1],[3,6,2],[3,3,7]])
#b=np.array([1,0,4])
#System 2
#A=np.array([[10,-1,0],[-1,10,-2],[0,-2,10]])
#b=np.array([9,7,6])
#System 3
#A=np.array([[10,5,0,0],[5,10,-4,0],[0,-4,8,-1],[0,0,-1,5]])
#b=np.array([6,25,-11,-11])
#System 4
#A=np.array([[4,1,1,0,1],[-1,-3,1,1,0],[2,1,5,-1,-1],[-1,-1,-1,4,0],[0,2,-1,1,4]])
#b=np.array([6,6,6,6,6])

#X_actual=np.linalg.solve(A,b).tolist()
n=5
X=[]
x0=np.zeros(n).tolist()
X.append(x0)

#Initialize
xk=np.zeros(n).tolist()
N=0
w=1.25
while N<n:
    x=np.zeros(n).tolist()
    for i in range(n):
        S=0
        for j in range(n):
            if (i!=j):
                S=S-A[i][j]*xk[j]
            
        m=(1-w)*xk[i] + w*(S + b[i])/A[i][i]
        xk[i]=m
        x[i]=m
    X.append(x)
    l=len(X)
    N=0
    for i in range(n):
        if abs(X[l-1][i]-X_actual[i])<0.01:
            N=N+1
    
l=len(X)
print("No of Iterations: ",l-1)
for i in range(l):
    print(np.transpose(X[i]))

No of Iterations:  7
[0. 0. 0. 0. 0.]
[ 6.25        0.4296875  -0.05875651 -0.41870117  0.01247675]
[ 7.40305583  0.40261432 -0.06813354 -0.49775864  0.00984042]
[ 7.68442818  0.42154101 -0.07136675 -0.52326829  0.01070397]
[ 7.78189882  0.42099463 -0.07256449 -0.53257501  0.0105493 ]
[ 7.82352548  0.42231612 -0.07311119 -0.53686231  0.010619  ]
[ 7.84250543  0.42258334 -0.07336146 -0.53884142  0.0106153 ]
[ 7.85152701  0.42277371 -0.07348303 -0.53978369  0.01062286]


### Conjugate Gradient Methods

In [33]:
#A=np.array([[0.1,0.2],[0.2,113]])
#b=np.array([0.3,113.2])

In [53]:
A=np.array([[0.2,0.1,1,1,0],[0.1,4,-1,1,-1],[1,-1,60,0,-2],[1,1,0,8,4],[0,-1,-2,4,700]])
b=np.array([1,2,3,4,5])
X_actual=[7.859713071, 0.422926408, -0.073592239, -0.540643016, 0.010626163]
n=5
X=[]
x0=np.zeros(n)
mod_r=1.0
r0=b-np.dot(A,x0)
p0=b-np.dot(A,x0)
N=0
while N<n:
    N=np.dot(r0.transpose(),r0)
    D=np.dot(np.dot(p0.transpose(),A),p0)
    alpha=N/D
    x1=x0+alpha*p0
    r1=r0-alpha*np.dot(A,p0)
    beta=(np.linalg.norm(r1)/np.linalg.norm(r0))**2
    p1=r1+beta*p0
    p0=p1
    x0=x1
    r0=r1
    X.append(x1)
    l=len(X)
    N=0
    for i in range(n):
        if abs(X[l-1][i]-X_actual[i])<0.01:
            N=N+1

l=len(X)
print("No of Iterations: ",l)
for i in range(l):
    print(np.transpose(X[i]))

No of Iterations:  5
[0.00300832 0.00601665 0.00902497 0.0120333  0.01504162]
[0.04647092 0.09363862 0.12985331 0.18422967 0.00632678]
[0.127921   0.26835779 0.05196309 0.493859   0.00484866]
[0.3059927  0.49147673 0.05351802 0.38951203 0.00577334]
[ 7.85971308  0.42292641 -0.07359224 -0.54064302  0.01062616]


In [7]:
np.linalg.norm(b)

113.20039752580377

In [12]:
np.sqrt(np.dot(b.transpose(),b))

113.20039752580377

# Question 17

### QR decomposition

In [79]:
A=np.array([[5,-2],[-2,8]])
V=np.array([[1,0],[0,1]])
S=0
n=2
N=0
while N<n*n-n:
    Q,R=np.linalg.qr(A)
    A=np.dot(R,Q)
    for i in range(n):
        for j in range(n):
            if (i!=j):
                if (abs(A[i][j])<0.001) :
                    N=N+1
Matrix(A)

Matrix([
[    8.99999992942521, -0.000594031912250446],
[-0.00059403191225076,      4.00000007057478]])

In [78]:
print("Eigenvalues of A using QR decomposition are:")
print(A[0][0],"&",A[1][1],".")

Eigenvalues of A using QR decomposition are:
8.999999929425208 & 4.000000070574784 .


In [74]:
A=np.array([[5,-2],[-2,8]])
Eigen_value, Eigen_vector=np.linalg.eigh(A)
Eigen_value

array([4., 9.])

# Question 18

### Power Method

In [83]:
b=np.array([2,3])
np.dot(b,b)

13

In [130]:
A=np.array([[2,-1,0],[-1,2,-1],[0,-1,2]])
x=np.array([1,1,1])
y=np.array([1,0,0])
D=np.dot(x.transpose(),y)
del_lamda=1
lamda0=0
I=np.array([[1,0,0],[0,1,0],[0,0,1]])
Am=np.dot(I,x)
while del_lamda >0.001:
    Am=np.dot(A,Am)
    lamda1=np.dot(Am.transpose(),y)/D
    del_lamda=np.abs(lamda1-lamda0)
    lamda0= lamda1
    D=np.dot(Am.transpose(),y)
print("Dominant Eigenvalue:",lamda0)
Scaling_factor=Am[0]/0.5
print("Eigenvector:",Am/Scaling_factor)

Dominant Eigenvalue: 3.414141414141414
Eigenvector: [ 0.5        -0.70710059  0.5       ]


array([0.58578644, 2.        , 3.41421356])

In [120]:
A=np.array([[2,-1,0],[-1,2,-1],[0,-1,2]])
Eigen_value, Eigen_vector=np.linalg.eigh(A)
Eigen_value[2],Eigen_vector[2]

(3.414213562373095, array([ 0.5       ,  0.70710678, -0.5       ]))

# Question 19

### Singular Value Decomposition

#### System 1

In [228]:
A=np.array([[2,1],[1,0]])
start_time=time.time()
U,S,V_T=np.linalg.svd(A)
svd_time=time.time()-start_time

In [229]:
svd_time

0.0010027885437011719

In [230]:
Matrix(U)

Matrix([
[-0.923879532511287, -0.38268343236509],
[ -0.38268343236509, 0.923879532511287]])

In [231]:
def fill_up_with_zeros(S,m,n):
    S_extended=np.zeros((m,n))
    for i in range(len(S)):
        S_extended[i][i]=S[i]
    return S_extended
S= fill_up_with_zeros(S,2,2)
Matrix(S)

Matrix([
[2.4142135623731,                 0],
[              0, 0.414213562373095]])

In [225]:
Matrix(V_T)

Matrix([
[-0.923879532511287,  -0.38268343236509],
[  0.38268343236509, -0.923879532511287]])

In [232]:
Matrix(np.dot(np.dot(U,S),V_T))

Matrix([
[2.0,                   1.0],
[1.0, -3.81016887278921e-17]])

#### System 2

In [235]:
A=np.array([[2,1],[1,0],[0,1]])
start_time=time.time()
U,S,V_T=np.linalg.svd(A)
svd_time=time.time()-start_time

In [236]:
svd_time

0.0009996891021728516

In [237]:
Matrix(U)

Matrix([
[-0.912870929175277, 4.80183453304857e-17, -0.408248290463863],
[-0.365148371670111,   -0.447213595499958,  0.816496580927726],
[-0.182574185835055,    0.894427190999916,  0.408248290463863]])

In [238]:
S=fill_up_with_zeros(S,3,2)
Matrix(S)

Matrix([
[2.44948974278318,   0],
[               0, 1.0],
[               0,   0]])

In [239]:
Matrix(V_T)

Matrix([
[-0.894427190999916, -0.447213595499958],
[-0.447213595499958,  0.894427190999916]])

In [240]:
Matrix(np.dot(np.dot(U,S),V_T))

Matrix([
[                  2.0,                   1.0],
[                  1.0, -6.81060746346194e-17],
[-1.23617225865877e-16,                   1.0]])

#### System 3

In [245]:
A=np.array([[2,1],[-1,1],[1,1],[2,-1]])
start_time=time.time()
U,S,V_T=np.linalg.svd(A)
svd_time=time.time()-start_time

In [246]:
svd_time

0.0005145072937011719

In [247]:
Matrix(U)

Matrix([
[-0.632455532033676, -0.5,  -0.522293212310753, -0.277866515388441],
[ 0.316227766016838, -0.5,  -0.301968572864907,  0.747539283918866],
[-0.316227766016838, -0.5,   0.797047140702639,  0.121308925878299],
[-0.632455532033676,  0.5, -0.0272146444730205,  0.590981694408725]])

In [248]:
S=fill_up_with_zeros(S,4,2)
Matrix(S)

Matrix([
[3.16227766016838,   0],
[               0, 2.0],
[               0,   0],
[               0,   0]])

In [249]:
Matrix(V_T)

Matrix([
[-1.0,    0],
[   0, -1.0]])

In [250]:
Matrix(np.dot(np.dot(U,S),V_T))

Matrix([
[ 2.0,  1.0],
[-1.0,  1.0],
[ 1.0,  1.0],
[ 2.0, -1.0]])

#### System 4

In [251]:
A=np.array([[1,1,0],[-1,0,1],[0,1,-1],[1,1,-1]])
start_time=time.time()
U,S,V_T=np.linalg.svd(A)
svd_time=time.time()-start_time

In [252]:
svd_time

0.00135040283203125

In [253]:
Matrix(U)

Matrix([
[-0.436435780471985,    -0.408248290463863,     0.707106781186547, -0.377964473009227],
[ 0.436435780471985,     0.408248290463863,     0.707106781186548,  0.377964473009227],
[-0.436435780471985,     0.816496580927726, -1.77001981877615e-16, -0.377964473009227],
[-0.654653670707977, -7.49205180133081e-17, -1.19230075411084e-16,  0.755928946018454]])

In [256]:
S=fill_up_with_zeros(S,4,3)
Matrix(S)

Matrix([
[2.64575131106459,   0,   0],
[               0, 1.0,   0],
[               0,   0, 1.0],
[               0,   0,   0]])

In [257]:
Matrix(V_T)

Matrix([
[-0.577350269189626, -0.577350269189626,  0.577350269189626],
[-0.816496580927726,  0.408248290463863, -0.408248290463863],
[                 0,  0.707106781186547,  0.707106781186548]])

In [258]:
Matrix(np.dot(np.dot(U,S),V_T))

Matrix([
[                 1.0,                   1.0, 1.33393445633273e-16],
[                -1.0, -1.99673461754274e-16,                  1.0],
[1.61842956344201e-16,                   1.0,                 -1.0],
[                 1.0,                   1.0,                 -1.0]])

#### System 5

In [259]:
A=np.array([[0,1,1],[0,1,0],[1,1,0],[0,1,0],[1,0,1]])
start_time=time.time()
U,S,V_T=np.linalg.svd(A)
svd_time=time.time()-start_time

In [260]:
svd_time

0.004439115524291992

In [262]:
Matrix(U)

Matrix([
[-0.547722557505166, -5.49521712695283e-16,    -0.707106781186548, -0.132058462551819, -0.42727106439408],
[-0.365148371670111,    -0.408248290463863,  5.43210214943126e-17, -0.543516408333063,  0.63607382737598],
[-0.547722557505166,  4.24980527316951e-16,     0.707106781186548, -0.132058462551819, -0.42727106439408],
[-0.365148371670111,    -0.408248290463863,  4.25921500823187e-17,  0.807633333436701,  0.21846830141218],
[-0.365148371670111,     0.816496580927726, -5.15968331031669e-16,  0.132058462551819,  0.42727106439408]])

In [261]:
S=fill_up_with_zeros(S,5,3)
Matrix(S)

Matrix([
[2.23606797749979,               0,   0],
[               0, 1.4142135623731,   0],
[               0,               0, 1.0],
[               0,               0,   0],
[               0,               0,   0]])

In [263]:
Matrix(V_T)

Matrix([
[-0.408248290463863,   -0.816496580927726, -0.408248290463863],
[ 0.577350269189626,   -0.577350269189626,  0.577350269189625],
[ 0.707106781186547, 3.86299829349208e-17, -0.707106781186548]])

In [264]:
Matrix(np.dot(np.dot(U,S),V_T))

Matrix([
[-3.32444578855373e-16,                   1.0,     0.999999999999999],
[-2.06450527071475e-16,                   1.0, -1.67647666288741e-16],
[                  1.0,     0.999999999999999, -3.03871955379186e-16],
[-2.14744091582561e-16,                   1.0, -1.59354101777655e-16],
[                  1.0, -3.44349857073541e-16,                   1.0]])

# Question 9

##### Jacobi method under L_inf norm

In [64]:
#System 1
A=np.array([[3,-1,1],[3,6,2],[3,3,7]])
b=np.array([1,0,4])
n=3
X=[]
x0=np.zeros(n)
X.append(x0)
#Initialize
xk=np.zeros(n)
SS=1.0
while SS>0.1:
    x=np.zeros(n)
    for i in range(n):
        xkm1=xk
        S=0
        for j in range(n):
            if (i!=j):
                S=S-A[i][j]*xkm1[j]
            
        x[i]=(S + b[i])/A[i][i]
    xk=x
    X.append(x)
    l=len(X)
    if l>1:
        s1=larg(X[l-1])
        s2=larg(X[l-2])
        SS=abs((s1-s2)*100/s2)

l=len(X)
print("No of Iterations: ",l-1)
for i in range(l):
    print("x",i,":",X[i])

No of Iterations:  10
x 0 : [0. 0. 0.]
x 1 : [0.33333333 0.         0.57142857]
x 2 : [ 0.14285714 -0.35714286  0.42857143]
x 3 : [ 0.07142857 -0.21428571  0.66326531]
x 4 : [ 0.04081633 -0.25680272  0.63265306]
x 5 : [ 0.03684807 -0.23129252  0.66399417]
x 6 : [ 0.03490444 -0.23975543  0.6547619 ]
x 7 : [ 0.03516089 -0.23570619  0.65922185]
x 8 : [ 0.03502399 -0.23732106  0.65737656]
x 9 : [ 0.03510079 -0.23663751  0.65812732]
x 10 : [ 0.03507839 -0.23692617  0.65780145]


C:\Users\HP\AppData\Local\Temp/ipykernel_23316/649561500.py:27: RuntimeWarning: divide by zero encountered in double_scalars
  SS=abs((s1-s2)*100/s2)


# Question 10

##### Gauss-Seidel method under L_inf norm

In [65]:
#System 1
A=np.array([[3,-1,1],[3,6,2],[3,3,7]])
b=np.array([1,0,4])

n=3
X=[]
x0=np.zeros(n).tolist()
X.append(x0)

#Initialize
xk=np.zeros(n).tolist()
SS=1.0
while SS>0.1:
    x=np.zeros(n).tolist()
    for i in range(n):
        S=0
        for j in range(n):
            if (i!=j):
                S=S-A[i][j]*xk[j]
            
        m=(S + b[i])/A[i][i]
        xk[i]=m
        x[i]=m
    X.append(x)
    l=len(X)
    if l>1:
        s1=larg(X[l-1])
        s2=larg(X[l-2])
        SS=abs((s1-s2)*100/s2)
        print(SS)
    
    
l=len(X)
print("No of Iterations: ",l-1)
for i in range(l):
    print("x",i,":",X[i])

inf
23.809523809523792
4.761904761904774
1.0905760905760855
0.26548707270112515
0.0638446868108856
No of Iterations:  6
x 0 : [0.0, 0.0, 0.0]
x 1 : [0.3333333333333333, -0.16666666666666666, 0.5]
x 2 : [0.11111111111111112, -0.22222222222222224, 0.619047619047619]
x 3 : [0.05291005291005294, -0.2328042328042328, 0.6485260770975056]
x 4 : [0.039556563366087184, -0.23595364071554548, 0.6555987474354821]
x 5 : [0.03614920394965748, -0.2366075177866561, 0.6573392773587138]
x 6 : [0.0353510682848767, -0.23678862659534294, 0.6577589535616284]


C:\Users\HP\AppData\Local\Temp/ipykernel_23316/1673056587.py:29: RuntimeWarning: divide by zero encountered in double_scalars
  SS=abs((s1-s2)*100/s2)
